import { Character } from '@/types/game';

/**
 * 24 characters for the Guess Who board.
 * Designed with good attribute distribution so questions are always meaningful.
 */
export const characters: Character[] = [
  {
    id: 'alex',
    name: 'Alex',
    avatar: '/characters/alex.png',
    attributes: {
      glasses: true,
      facialHair: false,
      hairColor: 'brown',
      hat: false,
      genderPresentation: 'masculine',
      smile: true,
      accessories: [],
      hairLength: 'short',
      eyeColor: 'brown',
    },
  },
  {
    id: 'bella',
    name: 'Bella',
    avatar: '/characters/bella.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'blonde',
      hat: false,
      genderPresentation: 'feminine',
      smile: true,
      accessories: ['earrings'],
      hairLength: 'long',
      eyeColor: 'blue',
    },
  },
  {
    id: 'carlos',
    name: 'Carlos',
    avatar: '/characters/carlos.png',
    attributes: {
      glasses: false,
      facialHair: true,
      hairColor: 'black',
      hat: true,
      genderPresentation: 'masculine',
      smile: false,
      accessories: [],
      hairLength: 'short',
      eyeColor: 'brown',
    },
  },
  {
    id: 'diana',
    name: 'Diana',
    avatar: '/characters/diana.png',
    attributes: {
      glasses: true,
      facialHair: false,
      hairColor: 'red',
      hat: false,
      genderPresentation: 'feminine',
      smile: true,
      accessories: ['necklace'],
      hairLength: 'medium',
      eyeColor: 'green',
    },
  },
  {
    id: 'ethan',
    name: 'Ethan',
    avatar: '/characters/ethan.png',
    attributes: {
      glasses: false,
      facialHair: true,
      hairColor: 'brown',
      hat: false,
      genderPresentation: 'masculine',
      smile: true,
      accessories: ['bowtie'],
      hairLength: 'medium',
      eyeColor: 'blue',
    },
  },
  {
    id: 'fiona',
    name: 'Fiona',
    avatar: '/characters/fiona.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'black',
      hat: true,
      genderPresentation: 'feminine',
      smile: false,
      accessories: ['earrings', 'necklace'],
      hairLength: 'long',
      eyeColor: 'brown',
    },
  },
  {
    id: 'george',
    name: 'George',
    avatar: '/characters/george.png',
    attributes: {
      glasses: true,
      facialHair: true,
      hairColor: 'gray',
      hat: false,
      genderPresentation: 'masculine',
      smile: false,
      accessories: [],
      hairLength: 'short',
      eyeColor: 'brown',
    },
  },
  {
    id: 'hannah',
    name: 'Hannah',
    avatar: '/characters/hannah.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'brown',
      hat: false,
      genderPresentation: 'feminine',
      smile: true,
      accessories: ['headband'],
      hairLength: 'medium',
      eyeColor: 'green',
    },
  },
  {
    id: 'ivan',
    name: 'Ivan',
    avatar: '/characters/ivan.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'blonde',
      hat: true,
      genderPresentation: 'masculine',
      smile: true,
      accessories: ['scarf'],
      hairLength: 'short',
      eyeColor: 'blue',
    },
  },
  {
    id: 'jade',
    name: 'Jade',
    avatar: '/characters/jade.png',
    attributes: {
      glasses: true,
      facialHair: false,
      hairColor: 'black',
      hat: false,
      genderPresentation: 'feminine',
      smile: false,
      accessories: [],
      hairLength: 'short',
      eyeColor: 'brown',
    },
  },
  {
    id: 'kevin',
    name: 'Kevin',
    avatar: '/characters/kevin.png',
    attributes: {
      glasses: false,
      facialHair: true,
      hairColor: 'red',
      hat: false,
      genderPresentation: 'masculine',
      smile: false,
      accessories: [],
      hairLength: 'medium',
      eyeColor: 'green',
    },
  },
  {
    id: 'luna',
    name: 'Luna',
    avatar: '/characters/luna.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'white',
      hat: false,
      genderPresentation: 'feminine',
      smile: true,
      accessories: ['earrings'],
      hairLength: 'long',
      eyeColor: 'blue',
    },
  },
  {
    id: 'marco',
    name: 'Marco',
    avatar: '/characters/marco.png',
    attributes: {
      glasses: true,
      facialHair: false,
      hairColor: 'black',
      hat: true,
      genderPresentation: 'masculine',
      smile: true,
      accessories: ['bowtie'],
      hairLength: 'short',
      eyeColor: 'brown',
    },
  },
  {
    id: 'nina',
    name: 'Nina',
    avatar: '/characters/nina.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'red',
      hat: true,
      genderPresentation: 'feminine',
      smile: false,
      accessories: ['scarf'],
      hairLength: 'medium',
      eyeColor: 'brown',
    },
  },
  {
    id: 'oscar',
    name: 'Oscar',
    avatar: '/characters/oscar.png',
    attributes: {
      glasses: false,
      facialHair: true,
      hairColor: 'brown',
      hat: false,
      genderPresentation: 'masculine',
      smile: false,
      accessories: ['necklace'],
      hairLength: 'bald',
      eyeColor: 'brown',
    },
  },
  {
    id: 'penny',
    name: 'Penny',
    avatar: '/characters/penny.png',
    attributes: {
      glasses: true,
      facialHair: false,
      hairColor: 'blonde',
      hat: false,
      genderPresentation: 'feminine',
      smile: true,
      accessories: [],
      hairLength: 'short',
      eyeColor: 'green',
    },
  },
  {
    id: 'quinn',
    name: 'Quinn',
    avatar: '/characters/quinn.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'brown',
      hat: true,
      genderPresentation: 'masculine',
      smile: true,
      accessories: [],
      hairLength: 'medium',
      eyeColor: 'blue',
    },
  },
  {
    id: 'rosa',
    name: 'Rosa',
    avatar: '/characters/rosa.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'black',
      hat: false,
      genderPresentation: 'feminine',
      smile: true,
      accessories: ['necklace', 'earrings'],
      hairLength: 'long',
      eyeColor: 'brown',
    },
  },
  {
    id: 'sam',
    name: 'Sam',
    avatar: '/characters/sam.png',
    attributes: {
      glasses: true,
      facialHair: true,
      hairColor: 'blonde',
      hat: false,
      genderPresentation: 'masculine',
      smile: false,
      accessories: [],
      hairLength: 'short',
      eyeColor: 'blue',
    },
  },
  {
    id: 'tara',
    name: 'Tara',
    avatar: '/characters/tara.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'gray',
      hat: true,
      genderPresentation: 'feminine',
      smile: false,
      accessories: ['headband'],
      hairLength: 'medium',
      eyeColor: 'green',
    },
  },
  {
    id: 'umar',
    name: 'Umar',
    avatar: '/characters/umar.png',
    attributes: {
      glasses: false,
      facialHair: true,
      hairColor: 'black',
      hat: false,
      genderPresentation: 'masculine',
      smile: true,
      accessories: ['scarf'],
      hairLength: 'short',
      eyeColor: 'brown',
    },
  },
  {
    id: 'violet',
    name: 'Violet',
    avatar: '/characters/violet.png',
    attributes: {
      glasses: true,
      facialHair: false,
      hairColor: 'brown',
      hat: false,
      genderPresentation: 'feminine',
      smile: false,
      accessories: ['earrings'],
      hairLength: 'long',
      eyeColor: 'blue',
    },
  },
  {
    id: 'will',
    name: 'Will',
    avatar: '/characters/will.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'red',
      hat: false,
      genderPresentation: 'masculine',
      smile: true,
      accessories: [],
      hairLength: 'bald',
      eyeColor: 'green',
    },
  },
  {
    id: 'xena',
    name: 'Xena',
    avatar: '/characters/xena.png',
    attributes: {
      glasses: false,
      facialHair: false,
      hairColor: 'white',
      hat: true,
      genderPresentation: 'feminine',
      smile: true,
      accessories: ['necklace'],
      hairLength: 'short',
      eyeColor: 'brown',
    },
  },
];

/**
 * Suggested questions that can be dynamically filtered
 * based on remaining characters on the board.
 */
export interface SuggestedQuestion {
  text: string;
  filter: (c: Character) => boolean;
}

export const suggestedQuestions: SuggestedQuestion[] = [
  { text: 'Do they wear glasses?', filter: (c) => c.attributes.glasses },
  { text: 'Do they have facial hair?', filter: (c) => c.attributes.facialHair },
  { text: 'Are they wearing a hat?', filter: (c) => c.attributes.hat },
  { text: 'Are they smiling?', filter: (c) => c.attributes.smile },
  { text: 'Do they have black hair?', filter: (c) => c.attributes.hairColor === 'black' },
  { text: 'Do they have brown hair?', filter: (c) => c.attributes.hairColor === 'brown' },
  { text: 'Do they have blonde hair?', filter: (c) => c.attributes.hairColor === 'blonde' },
  { text: 'Do they have red hair?', filter: (c) => c.attributes.hairColor === 'red' },
  { text: 'Do they have gray or white hair?', filter: (c) => c.attributes.hairColor === 'gray' || c.attributes.hairColor === 'white' },
  { text: 'Do they have long hair?', filter: (c) => c.attributes.hairLength === 'long' },
  { text: 'Do they have short hair?', filter: (c) => c.attributes.hairLength === 'short' },
  { text: 'Are they bald?', filter: (c) => c.attributes.hairLength === 'bald' },
  { text: 'Do they look masculine?', filter: (c) => c.attributes.genderPresentation === 'masculine' },
  { text: 'Do they look feminine?', filter: (c) => c.attributes.genderPresentation === 'feminine' },
  { text: 'Do they have blue eyes?', filter: (c) => c.attributes.eyeColor === 'blue' },
  { text: 'Do they have brown eyes?', filter: (c) => c.attributes.eyeColor === 'brown' },
  { text: 'Do they have green eyes?', filter: (c) => c.attributes.eyeColor === 'green' },
  { text: 'Do they wear earrings?', filter: (c) => c.attributes.accessories.includes('earrings') },
  { text: 'Do they wear a necklace?', filter: (c) => c.attributes.accessories.includes('necklace') },
  { text: 'Do they wear a bowtie?', filter: (c) => c.attributes.accessories.includes('bowtie') },
  { text: 'Do they wear a scarf?', filter: (c) => c.attributes.accessories.includes('scarf') },
  { text: 'Do they have any accessories?', filter: (c) => c.attributes.accessories.length > 0 },
];

/**
 * Get useful suggested questions based on remaining characters.
 * Filters out questions that would apply to ALL or NONE of the remaining characters
 * (since those questions wouldn't help narrow down the board).
 */
export function getUsefulQuestions(
  remainingCharacters: Character[]
): SuggestedQuestion[] {
  if (remainingCharacters.length <= 1) return [];

  return suggestedQuestions.filter((q) => {
    const matchCount = remainingCharacters.filter(q.filter).length;
    // Only useful if it splits the remaining characters (not all, not none)
    return matchCount > 0 && matchCount < remainingCharacters.length;
  });
}
